### ISSUE TITLE
Package warns of being outdated

### ISSUE THREAD

**Issue by slankes** [flathub/ch.threema.threema-web-desktop#1]
Running the flatpak you get a message that it is out of date (apparently this is started after 120 days).

**Comment by slankes** [comment]
This is version 1.1.0 and the latest one downloadable as rpm seems to be 2.4.2 (1.2.18).

**Comment by ljrk0** [comment]
Hey, thanks for the report!

This is interesting as I'm running this fine and it doesn't complain here.  The version should be 1.1.10-web-2.3.19 since this is just web.threema.ch in version 2.3.19 in an Electron.  Should be updated regardless, I simply didn't because there were some problems w.r.t. the CI pipeline for some time.  I'll check up on this.

**Comment by ljrk0** [comment]
It's now in the official build pipeline but you can use the test build from #2 as long as it's not published yet.  Should be automatically online within the next 3-4 hours.

**Comment by y20k** [comment]
Hi @ljrk0 

I today got the message "App Is Not up to Date", too.

![Screenshot from 2023-07-10 09-26-44](https://github.com/flathub/ch.threema.threema-web-desktop/assets/9103935/292cddfb-332a-41f7-bd04-a9b8e35e3579)
