### ISSUE TITLE
Update Request: Bump to v2.5.1

### ISSUE THREAD

**Issue by Saijin-Naib** [flathub/ch.threema.threema-web-desktop#5]
Sorry to bother again, but could this get bumped to v2.5.1? I'm working with Threema support on some intermittent file send/receive issues, and this might be a contributing factor.

This release mostly is concerned with dependency bumps.

https://github.com/threema-ch/threema-web/blob/master/CHANGELOG.md

**Comment by ljrk0** [comment]
Thank you for bringing this to my attention (you're not bothering at all)!  However, I'm a bit conflicted since usually on Flathub we try to package as faithfully as possible and the Threema Electron app is still at 2.5.0.  I've created a PR upstream to address this issue however:

https://github.com/threema-ch/threema-web-electron/pull/7

**Comment by Saijin-Naib** [comment]
Ahhh, makes sense. Must just be the web platform that got pushed to v2.5.2.

Is there an easy guide for me to contribute if a bump is an easy change?

I'm not versed with Flatpak at all, but I have some minor experience packaging for Alpine Linux.

**Comment by ljrk0** [comment]
In theory, updating is easy and I documented the steps I take in the README.  This change https://github.com/flathub/ch.threema.threema-web-desktop/commit/771ae06074820f17f3d9f9005141aadf13dc6c88 demonstrates that it's *basically* just pointing the YAML which describes the sources to the right commit.  However, due to the nature of how Flathub builds, we need to usually do a few other things as well.

Basically, Flathub has a very clear distinction between the source-fetch and the build process.  There's no Internet connectivity in the latter!  So build engines such as `npm` or `cargo` often just fail since they download necessary dependencies on build time.  To work around that we parse the `package-lock.json`, `Cargo.toml`, or whatever file, pre-fetch the sources and cache them to be used in the build.  This is done by generating a `generated-sources.json` listing all URLs for the pre-fetched sources.  So with each update we need to

1. Update a local clone of the Threema Electron repo including all of its submodules
2. Re-generate aforementioned `generated-sources.json`
3. Bump the commit in the YAML

This *should* do it as long there are no changes in the build process.  However, as you can see in https://github.com/flathub/ch.threema.threema-web-desktop/commit/942c98521e2dac738f61204b617f99a8b9802590 sometimes we need to workaround upstream since the 1.2.21 build was broken: They pointed the submodule to the wrong tag.  Hence I had to manually point it to a more recent version.

Similarly, upstream regularly forgets to update the metadata file with new release date information which has to be patched as well.

Finally, test the build :-)

It would be much easier if the release process was much more consistent, then I could theoretically just set-up CI to do the mentioned 3-step-process.  But currently that's not worth the effort, especially since Threema is phasing out the Electron client.

**Comment by ljrk0** [comment]
In the meantime, upstream has updated to 2.5.1 with Threema Web Desktop 1.2.29/31, and I've created https://github.com/flathub/ch.threema.threema-web-desktop/pull/6 to address this :)

**Comment by ljrk0** [comment]
Closed by #6
